New handler for Metering point created and Energy supplier changed
Energinet-DataHub/geh-market-roles pull request #1332
Opened 2022-09-27 08:37 UTC by Mathiesen

## Description

Added a new handler that handles metering point created and implemented a new handler for energy supplier changed

## References

#1015

2022-09-27 10:38 UTC, kft commented on source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081222 Add gridoperatorid to market evaluation point.sql
> +    ADD GridOperatorId [nvarchar](50) NULL
Why change this ?

2022-09-27 10:39 UTC, kft commented on source/Messaging.Application/MasterData/MarketEvaluationPoints/CreateMarketEvalationPoint.cs
> +        string gridOperatorId = "",
GridOperatorId is a GUID

2022-09-27 10:40 UTC, kft commented on source/Messaging.Domain/MasterData/MarketEvaluationPoints/MarketEvaluationPoint.cs
> +        Id = Guid.NewGuid();
Id should the Id of the metering point. It kan be parsed from the event

2022-09-27 10:41 UTC, Mathiesen commented on source/Messaging.Domain/MasterData/MarketEvaluationPoints/MarketEvaluationPoint.cs
> +        Id = Guid.NewGuid();
Will do

2022-09-27 10:42 UTC, kft commented on source/Messaging.IntegrationTests/Application/MasterData/MarketEvaluationPoints/CreateMarketEvaluationPointTests.cs
> +            Transactions.MoveIn.SampleData.IdOfGridOperatorForMeteringPoint.ToString());
Use sample data specific for this scenario. Otherwise your test is not isolated anymore

2022-09-27 10:45 UTC, Korgath commented on source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081222 Add gridoperatorid to market evaluation point.sql
> +    ADD GridOperatorId [nvarchar](50) NULL
Arent't it still guids coming in?

2022-09-27 10:45 UTC, kft commented on source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp/Scripts/Model/202226081222 Add gridoperatorid to market evaluation point.sql
> +    ADD GridOperatorId [nvarchar](50) NULL
Yes

2022-09-28 07:03 UTC, Korgath requested changes

2022-09-28 07:03 UTC, Korgath commented on source/Messaging.IntegrationTests/Application/MasterData/MarketEvaluationPoints/CreateMarketEvaluationPointTests.cs
> +    : TestBase, IAsyncLifetime
something seems off with this class - why do we need to implement IAsyncLifeTime? there is no need in any other test classes and testbase disposes?

2022-09-28 10:46 UTC, Korgath approved these changes

2022-09-28 20:30 UTC, merged