Add logic for cancellation and effectuation of change of supplier business process
Energinet-DataHub/geh-market-roles pull request #200
Opened 2021-04-21 18:05 UTC by kft

## Description

This PR adds logic for Cancellation and Effectuation of change of supplier business processes. This is handled by the `AccountingPoint` aggregate.

A business process can be effectuated only on- or after the defined `EffectiveDate`. Upon effectuation, the current supplier is marked as "ended" by setting the `EndOfSupplyDate` on the corresponding `SupplierRegistration`. The future/new supplier is marked as the current supplier by setting the `StartOfSupplyDate` on the corresponding `SupplierRegistration`.
The business process is marked as `Completed`. 

A business process can be cancelled only while status is `Pending`.

Functionality is demostrated with corresponding Dev/Unit tests.

## References

2021-04-21 19:00 UTC, Sondergaard commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/ConsumerRegistrationSnapshot.cs
> +    public class ConsumerRegistrationSnapshot
Could this be replaced with `record` type to reduce boilerplate code?

https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records

2021-04-22 06:08 UTC, cmgrd approved these changes
The comment about IsBroken is only marked once but happens multiple times. If you disagree just disregard that comment.

2021-04-22 06:08 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/Rules/ChangeEnergySupplier/ChangeOfSupplierRegisteredOnSameDateIsNotAllowedRule.cs
>          public bool IsBroken => ProcessAlreadyRegistered();
Should we consider flipping IsBroken to IsValid - as we did with the validation?

2021-04-22 06:08 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketData.Infrastructure/DataPersistence/MarketEvaluationPoints/MarketEvaluationPointRepository.cs
> +            // var meteringPointSnapshot = new MeteringPointSnapshot(
Is the commented-out code still needed?

2021-04-22 06:57 UTC, cmgrd requested changes

2021-04-22 06:57 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/AccountingPoint.cs
> +            futureSupplier.StartOfSupply(businessProcess.EffectiveDate);
GetCurrentSupplier returns a nullable but we assume not null on line 148.
On line 151 we also assume not null for the future supplier. Should we wrap that in a method as we did with GetCurrentSupplier and then return a non-nullable for both methods?

2021-04-22 06:57 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/AccountingPoint.cs
> +        private BusinessProcess GetBusinessProcessOrThrow(ProcessId processId, BusinessProcessType businessProcessType)
What value does the OrThrow part of the name add? I can see it's used throughout the PR.

2021-04-22 11:14 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/ConsumerRegistrationSnapshot.cs
> +    public class ConsumerRegistrationSnapshot
Sure it could. But I will prefer to address it in another PR :-)

2021-04-22 11:18 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/Rules/ChangeEnergySupplier/ChangeOfSupplierRegisteredOnSameDateIsNotAllowedRule.cs
>          public bool IsBroken => ProcessAlreadyRegistered();
IsValid makes sence when the object is a Result. But here we are talking about a Rule. And a rule can be "Violated" or "Broken" :-)

2021-04-22 11:52 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/AccountingPoint.cs
> +        private BusinessProcess GetBusinessProcessOrThrow(ProcessId processId, BusinessProcessType businessProcessType)
It is just to make the posible side-effect clear.

2021-04-22 11:53 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketData.Infrastructure/DataPersistence/MarketEvaluationPoints/MarketEvaluationPointRepository.cs
> +            // var meteringPointSnapshot = new MeteringPointSnapshot(
Yes it is. The repository part will be fixed in another PR.

2021-04-22 12:39 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/Rules/ChangeEnergySupplier/BusinessProcessStatus.cs
> +
Do we need a state for the period between pending and completed? This is relevant for processes with a cancellation period that ends before the effectuation date. Meaning once cancellation period expires there can still be time until the effectuation date, but as the cancellation period is expired the supplier cannot cancel it anymore, and therefore the stipulation that only "pending" process status can be cancelled is wrong.

2021-04-22 12:39 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/Rules/ChangeEnergySupplier/ChangeOfSupplierRegisteredOnSameDateIsNotAllowedRule.cs
>          public bool IsBroken => ProcessAlreadyRegistered();
Violated is better than broken as it is more specific. Broken can have several interpretations

2021-04-22 12:39 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/MeteringPointSnapshot.cs
>      public class MeteringPointSnapshot
Shouldn't this be "AccountingPointSnapshot"?

2021-04-22 12:39 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketData.Tests/Domain/MeteringPoints/MoveInTests.cs
> +        public void Effectuate_WhenAheadOfEffectiveDate_IsNotPossible()
Just to confirm, ahead means before? If so we should change naming to be unambiguous

2021-04-22 12:39 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketData.Tests/Domain/MeteringPoints/MoveInTests.cs
> +        public void Effectuate_WhenAheadOfEffectiveDate_IsNotPossible()
This goes for other tests with same naming also

2021-04-22 13:56 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/AccountingPoint.cs
> +        {
Grid area is not needed currently or child MP's. I guess it will be handled by the MP domain. If not, we will add it when required.

2021-04-22 13:57 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketData.Domain/MeteringPoints/AccountingPoint.cs
> +        }
This will be part of the validation at application level.

2021-04-22 13:59 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketData.Tests/Domain/MeteringPoints/MoveInTests.cs
> +        public void Effectuate_WhenAheadOfEffectiveDate_IsNotPossible()
Yes, it means before :-)

2021-04-23 07:32 UTC, MrDach commented on source/business-workflow/source/Energinet.DataHub.MarketData.Tests/Domain/MeteringPoints/MoveInTests.cs
> +        public void Effectuate_WhenAheadOfEffectiveDate_IsNotPossible()
Why not use the latin version "Ante" instead 😄

2021-04-23 12:59 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketData.Tests/Domain/MeteringPoints/MoveInTests.cs
> +        public void Effectuate_WhenAheadOfEffectiveDate_IsNotPossible()
Eller den sofisitikerede: Avant :p

2021-04-23 13:08 UTC, erduna approved these changes

2021-04-26 09:01 UTC, cmgrd approved these changes

2021-04-26 09:02 UTC, merged