Add pipelines and composition root setup
Energinet-DataHub/geh-market-roles pull request #297
Opened 2021-04-27 09:08 UTC by cmgrd

Adds pipeline behaviors.
Uses simpleinjector.
Adds a dummy implementation, to keep the flow intact.

2021-04-27 10:57 UTC, Korgath approved these changes

2021-04-27 11:12 UTC, Sondergaard requested changes
I would like to see that the ServiceBusClient injected into the class `ServiceBusProcessingClient`

Beside that it looks solid. 👍

2021-04-27 11:12 UTC, Sondergaard commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/ServiceBusProcessingClient.cs
> +            await using (ServiceBusClient client = new ServiceBusClient(connectionString))
Please inject the `ServiceBusClient` - this is due to performance.

For details read this [guide](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk-2#reusing-factories-and-clients)

2021-04-27 12:09 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/ServiceBusProcessingClient.cs
> +            await using (ServiceBusClient client = new ServiceBusClient(connectionString))
If was kind of hoping that this comment would keep me out of trouble 😁 

> TODO: This implementation is only for keeping a working flow in the RequestChangeOfSupplier workflow and thus should be re-implemented or deleted when refactoring.

For the sake of completeness, I've implemented it as suggested.

2021-04-27 12:26 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Application/ChangeOfSupplier/RequestChangeOfSupplier.cs
> +            string Transaction,
Should be processID, as we get a process ID but each generated message generates a transactionID that message is associated with

2021-04-27 12:32 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/CommandApi.cs
>              logger.LogInformation("C# HTTP trigger function processed a request.");
Can we in our logger information either print the associated message transaction ID or the process ID? Or both. Historically we have had a hard time tracking individual messages when debugging, so it would make sense we start using more telling loginfo.

2021-04-27 13:22 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion/CommandApi.cs
>              logger.LogInformation("C# HTTP trigger function processed a request.");
I think that's part of the not yet started story of monitoring.

2021-04-28 07:05 UTC, erduna approved these changes

2021-04-28 09:58 UTC, thbaan commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/ServiceBusProcessingClient.cs
> +            var bytes = Encoding.UTF8.GetBytes(System.Text.Json.JsonSerializer.Serialize(request));
Shouldn't we use an injected instance of IJsonSerializer rather than System.Text.Json.JsonSerializer directly?

2021-04-28 10:02 UTC, thbaan approved these changes

2021-04-28 11:16 UTC, merged