Protobuff contracts added
Energinet-DataHub/geh-market-roles pull request #592
Opened 2021-06-17 12:30 UTC by Korgath

## Description

Added EnergySupplierChangeAccepted, EnergySupplierChanged, EnergySupplierChangeCancelled contracts

## References

* #0000

2021-06-17 18:25 UTC, erduna approved these changes

2021-06-18 07:11 UTC, erduna requested changes
I have just added some comments documenting the contracts. Comments will be used for generating the .md later on.

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChangeAccepted.proto
> +
```suggestion
/**
 * This message is sent out when a energy supplier change is accepted. It informs who will be the future energy supplier of the respective metering point
 */
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChangeAccepted.proto
> +  string MeteringPointId = 1;
```suggestion
  string MeteringPointId = 1; // Unique metering point identification
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChangeAccepted.proto
> +  string EnergySupplierGLN = 2;
```suggestion
  string EnergySupplierGLN = 2; // Unique Energy Supplier identifcation
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChangeAccepted.proto
> +  string EffectiveDate = 3;
```suggestion
  string EffectiveDate = 3; // Date in which the supplier change will go into effect
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChangeAccepted.proto
> +  string TransactionId = 4;
```suggestion
  string TransactionId = 4; // Unique transaction ID of the process. Needed to effectuate the correct process at a later date.
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChangeCancelled.proto
> +  string TransactionId = 2;
```suggestion
  string TransactionId = 2; // Unique transaction ID of the process. Needed to cancel the correct process.
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChangeCancelled.proto
> +  string MeteringPointId = 1;
```suggestion
  string MeteringPointId = 1; // Unique metering point identification
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChanged.proto
> +  string MeteringPointId = 1;
```suggestion
  string MeteringPointId = 1; // Unique metering point identification
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChanged.proto
> +  string TransactionId = 4;
```suggestion
  string TransactionId = 4; // Unique transaction ID of the process. Needed to effectuate the correct accepted process.
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChanged.proto
> +  string EnergySupplierGLN = 2;
```suggestion
  string EnergySupplierGLN = 2; // Unique Energy Supplier identifcation.
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChanged.proto
> +  string EffectiveDate = 3;
```suggestion
  string EffectiveDate = 3; // Date which the change of supplier goes into effect.
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChangeCancelled.proto
> +
```suggestion
/**
 * This message is sent out when an awaiting change of energy supplier has been cancelled.
 */
```

2021-06-18 07:11 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/Contracts/EnergySupplierChanged.proto
> +
```suggestion
/**
 * This message is sent out when an energy supplier has been changed.
 */
```

2021-06-18 09:17 UTC, erduna approved these changes

2021-06-18 10:35 UTC, cmgrd approved these changes

2021-06-18 10:57 UTC, merged