Changed naming of contracts to be more telling
Energinet-DataHub/geh-market-roles pull request #600
Opened 2021-06-21 12:23 UTC by erduna

## Description

As agreed with team Joules and @Sondergaard we have renamed our contract names to better reflect future events.

## References

* #0000

2021-06-21 12:32 UTC, Korgath approved these changes

2021-06-21 13:48 UTC, kft requested changes
Public interfaces should be alligned internally in team prior to be exposed. Why are the events needed ? And do we expose internal properties ? (MeteingPointId, TransactionId)

2021-06-21 15:11 UTC, erduna commented
> Public interfaces should be alligned internally in team prior to be exposed. Why are the events needed ? And do we expose internal properties ? (MeteingPointId, TransactionId)

I have aligned it with other teams, with the architect and with the business. We can have another internal talk if needed :)

2021-06-23 10:41 UTC, Korgath approved these changes

2021-06-24 09:27 UTC, MrDach approved these changes
Only two minor suggestions but looks good otherwise.

2021-06-24 09:27 UTC, MrDach commented on docs/contracts.md
> +| EffectiveDate | [string](#string) |  | Date which the change of supplier goes into effect. |
Nit: Date **on** which

2021-06-24 09:27 UTC, MrDach commented on docs/contracts.md
> +| EffectiveDate | [string](#string) |  | Date in which the supplier change will go into effect |
Nit: Date **on** which

2021-06-24 09:36 UTC, MrDach approved these changes

2021-06-24 12:09 UTC, Korgath approved these changes

2021-06-24 13:24 UTC, merged