Dispatch ConsumerRegistered and EnergySupplierChanged to Service bus
Energinet-DataHub/geh-market-roles pull request #606
Opened 2021-06-25 11:41 UTC by Korgath

## Description

- Implemented Simpleinjector extension to handle injections of ProtoOutboundMappers
- Handling sending to multiple servicebus topics 
- Implemented handlers to dispatch integration events (ConsumerRegistered and EnergySupplierChanged) to shared servicebus
- Content Type of ServiceBusMessage set to application/octet-stream
- Added Energy Supplier Changed Topic to Terraform

## References

* #0000

2021-06-25 12:06 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/ChangeOfSupplier/Mappers/EnergySupplierChangedIntegrationMapper.cs
> +                EffectiveDate = obj.StartOfSupplyDate.ToString(),
This is missing the transactionId property? We could just leave it empty for now with a TODO comment?

2021-06-25 12:08 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/ChangeOfSupplier/Mappers/EnergySupplierChangedIntegrationMapper.cs
> +                EffectiveDate = obj.StartOfSupplyDate.ToString(),
Or use the correlation Id maybe if that's expected to be the transaction id

2021-06-25 12:19 UTC, erduna submitted a review, later dismissed
discussed and agreed on todos.

2021-06-25 12:33 UTC, Korgath commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/ChangeOfSupplier/Mappers/EnergySupplierChangedIntegrationMapper.cs
> +                EffectiveDate = obj.StartOfSupplyDate.ToString(),
As we discussed we will set the correlation Id as a property on the servicebus message object.
TODO here is to expand on our Outbox table so that it can hold the correelation id, which we then can set when fetching the events from the outbox table.
This will be a seperat task

2021-06-25 13:57 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/ChangeOfSupplier/Mappers/EnergySupplierChangedIntegrationMapper.cs
> +                EffectiveDate = obj.StartOfSupplyDate.ToString(),
Transaction or correlationid: none of these should be included in an integration event.

2021-06-25 19:05 UTC, Korgath commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEventDispatching/ChangeOfSupplier/Mappers/EnergySupplierChangedIntegrationMapper.cs
> +                EffectiveDate = obj.StartOfSupplyDate.ToString(),
@kft reasoning for correlation Id as a property on the service bus message would be for instrumentation and tracking purpose.
The timestamp is that for sequence? Because when a message is sent to a Topic it is automaticly given a Sequence number.
Anyway . lets talk Monday

2021-06-28 06:00 UTC, cmgrd requested changes

2021-06-28 13:44 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox/Program.cs
> +            container.AddProtobufOutBoundMappers(
nit: lower case b

2021-06-28 13:44 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Common/SimpleInjector/SimpleInjectorAddProtoBufContractsContainerExtensions.cs
> +        public static void AddProtobufOutBoundMappers(this Container container, Assembly[] applicationAssemblies)
nit: lower case b

2021-06-29 06:54 UTC, erduna approved these changes

2021-06-29 13:11 UTC, kft approved these changes

2021-06-29 13:26 UTC, merged