Input validations Request move in
Energinet-DataHub/geh-market-roles pull request #609
Opened 2021-06-29 13:22 UTC by Korgath

## Description

Input validations rule set for RequestMoveIn

## References

* #0000

2021-06-29 13:29 UTC, erduna submitted a review, later dismissed

2021-06-29 14:43 UTC, kft submitted a review, later dismissed

2021-06-29 18:09 UTC, cmgrd requested changes
I think the naming of the tests can be a bit confusing. I would suggest that we use simple phrases instead.

`Validate_WhenSocialSecurityNumber_IsSuccess` could be `Valid_social_security_number_should_result_in_success`

`Validate_WhenSocialSecurityNumber_IsFailure` could be `Invalid_social_security_number_should_result_in_error`

I even think we could come up with better names than my suggestions here...

2021-06-30 06:44 UTC, cmgrd approved these changes

2021-06-30 07:13 UTC, erduna approved these changes

2021-06-30 07:15 UTC, merged