Dph/add propertiesto cs proj
Energinet-DataHub/geh-market-roles pull request #611
Opened 2021-06-30 08:57 UTC by Korgath

## Description

Added the following properties to Domain CSProj:

<LangVersion>9.0</LangVersion>
<Nullable>enable</Nullable>
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
<GenerateDocumentationFile>true</GenerateDocumentationFile>

Fixed errors coming from this change

## References

* #0000

2021-06-30 10:16 UTC, erduna approved these changes

2021-06-30 10:39 UTC, cmgrd requested changes

2021-06-30 10:39 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Rules/ChangeEnergySupplier/MoveOutRegisteredOnSameDateIsNotAllowedRule.cs
> +    // }
Commented out code

2021-06-30 10:39 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/SeedWork/IBusinessRule.cs
> +        ValidationError ValidationError { get; }
Why the name change?

2021-06-30 10:39 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/Consumers/Consumer.cs
> +            AddDomainEvent(new ConsumerCreated(ConsumerId.Value, CprNumber?.Value, CvrNumber.Value, _name.FullName));
If the not-used property will be null, shouldn't we just pass null then? It cannot be both, right?

2021-06-30 10:39 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/SeedWork/BusinessRulesValidationResult.cs
> +        public ICollection<ValidationError> Errors { get; private set; } = new List<ValidationError>();
Why do we prefer a collection over a list?

2021-06-30 12:13 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/Consumers/CprNumber.cs
> +            return new BusinessRulesValidationResult(new Collection<IBusinessRule>()
Why change to collection ?

2021-06-30 12:56 UTC, Korgath commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/Consumers/Consumer.cs
> +            AddDomainEvent(new ConsumerCreated(ConsumerId.Value, CprNumber?.Value, CvrNumber.Value, _name.FullName));
Correct

2021-06-30 12:57 UTC, Korgath commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/Consumers/CprNumber.cs
> +            return new BusinessRulesValidationResult(new Collection<IBusinessRule>()
Lots of stylecop complaining implementing the properties - forgot to set this back to List.

2021-06-30 13:06 UTC, Korgath commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain/MeteringPoints/Rules/ChangeEnergySupplier/MoveOutRegisteredOnSameDateIsNotAllowedRule.cs
> +    // }
Yes, Part of the TODO. Just commented the last part out to make it build

2021-06-30 13:08 UTC, erduna approved these changes

2021-07-01 06:36 UTC, cmgrd approved these changes

2021-07-01 06:50 UTC, merged