Add XML Converter to Market Roles
Energinet-DataHub/geh-market-roles pull request #615
Opened 2021-07-01 13:17 UTC by thbaan

## Description

## References

* #0000

2021-07-01 21:50 UTC, Korgath approved these changes

2021-07-02 06:40 UTC, erduna requested changes
for change of supplier we also need to consider VAT/SSN

2021-07-02 06:40 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDIMessaging/XmlConverter/Mappings/ChangeOfSupplierXmlMappingConfiguration.cs
> +                .AddProperty(x => x.ConsumerId, "marketEvaluationPoint.customer_MarketParticipant.mRID")
This also needs to account for VAT/CPR, as you do in the requestmovein config

2021-07-02 06:40 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDIMessaging/XmlConverter/Mappings/ChangeOfSupplierXmlMappingConfiguration.cs
> +                .AddProperty(x => x.MeteringPointId, "marketEvaluationPoint.mRID")
Shouldn't this also be accountpoint gsrn, just as in the move in config?

2021-07-02 09:22 UTC, cmgrd approved these changes

2021-07-02 09:23 UTC, thbaan commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDIMessaging/XmlConverter/Mappings/ChangeOfSupplierXmlMappingConfiguration.cs
> +                .AddProperty(x => x.ConsumerId, "marketEvaluationPoint.customer_MarketParticipant.mRID")
This is out of scope of this PR. We should take care of this in a seperate task/story.

2021-07-02 09:23 UTC, thbaan commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDIMessaging/XmlConverter/Mappings/ChangeOfSupplierXmlMappingConfiguration.cs
> +                .AddProperty(x => x.MeteringPointId, "marketEvaluationPoint.mRID")
This is out of scope of this PR. We should take care of this in a seperate task/story.

2021-07-02 09:26 UTC, merged