use cim documents
Energinet-DataHub/geh-market-roles pull request #616
Opened 2021-07-02 08:31 UTC by cmgrd

2021-07-02 12:00 UTC, thbaan approved these changes

2021-07-02 12:05 UTC, thbaan approved these changes

2021-07-02 12:19 UTC, thbaan approved these changes

2021-07-03 19:46 UTC, erduna approved these changes

2021-07-06 12:30 UTC, kft approved these changes

2021-07-06 13:37 UTC, erduna requested changes

2021-07-06 13:37 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Acknowledgements/AcknowledgementXmlSerializer.cs
> +                    new XElement(xmlNamespace + "createdDateTime", message.CreatedDateTime),
missing businessSector.type

2021-07-06 13:37 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Acknowledgements/AcknowledgementXmlSerializer.cs
> +                    new XElement(xmlNamespace + "sender_MarketParticipant.marketRole.type", message.Sender.Role),
missing businessSector.type

2021-07-06 13:37 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Acknowledgements/ConfirmMessage.cs
> +        Instant CreatedDateTime,
missing missing businessSector.type

2021-07-06 13:37 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Acknowledgements/RejectMessage.cs
> +        MarketParticipant Receiver,
missing businessSector.type

2021-07-06 13:37 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/MoveIn/RequestMoveInResultHandler.cs
> +                CreatedDateTime: _dateTimeProvider.Now(),
missing businessSector.type

2021-07-06 13:37 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/MoveIn/RequestMoveInResultHandler.cs
> +                ReasonCode: "39",
missing businessSector.type

2021-07-06 17:32 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Acknowledgements/AcknowledgementXmlSerializer.cs
> +                    new XElement(xmlNamespace + "createdDateTime", message.CreatedDateTime),
Added.

2021-07-06 17:32 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Acknowledgements/AcknowledgementXmlSerializer.cs
> +                    new XElement(xmlNamespace + "sender_MarketParticipant.marketRole.type", message.Sender.Role),
Added.

2021-07-06 17:32 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Acknowledgements/ConfirmMessage.cs
> +        Instant CreatedDateTime,
Added.

2021-07-06 17:32 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Acknowledgements/RejectMessage.cs
> +        MarketParticipant Receiver,
Added.

2021-07-06 17:33 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/MoveIn/RequestMoveInResultHandler.cs
> +                CreatedDateTime: _dateTimeProvider.Now(),
Added.

2021-07-06 17:33 UTC, cmgrd commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/MoveIn/RequestMoveInResultHandler.cs
> +                ReasonCode: "39",
Added.

2021-07-06 19:10 UTC, erduna approved these changes

2021-07-06 19:56 UTC, Korgath approved these changes

2021-07-07 06:04 UTC, merged