Refactor: Integration event contracts
Energinet-DataHub/geh-market-roles pull request #624
Opened 2021-07-06 12:07 UTC by kft

## Description
In order to maintain cohesiveness and keep a clear overview of the codebase, protobuf contracts and mapper are moved to the same folder and the POCO class (Integration event) it self.

`EnergySupplierChanged` contract has been refactored to comply with protobuf style guide, and TransactionId has been removed.

A couple of contracts currently not used have been removed.

2021-07-06 12:34 UTC, erduna requested changes
refactor to gsrn in integration event is wrong, as we use entso-e and cim naming in integration. Please confirm with Preben if you'd like.

Also, I disagree with removing the contracts for cancellation and future supplier change, but if you want to reimplement them (while excluding transaction ID) in a few weeks, feel free :)

2021-07-06 12:34 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEvents/EnergySupplierChange/EnergySupplierChangedIntegrationEvent.proto
> +  string gsrn_number = 1; // Unique metering point identification
This is wrong. It is metering point ID as we are following ENTSO-E for domain naming and roles, and CIM internally. Checked with Preben, you are welcome to double check with him.

https://eepublicdownloads.entsoe.eu/clean-documents/EDI/Library/HRM/Harmonised_Role_Model_2020-01.pdf

2021-07-06 12:42 UTC, kft commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEvents/EnergySupplierChange/EnergySupplierChangedIntegrationEvent.proto
> +  string gsrn_number = 1; // Unique metering point identification
This has nothing to do CIM naming at all. This is an integration event. And integration events are not expressed in CIM. CIM is for EDI concerns.

2021-07-06 12:45 UTC, Korgath approved these changes

2021-07-06 12:50 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEvents/EnergySupplierChange/EnergySupplierChangedIntegrationEvent.proto
> +  string gsrn_number = 1; // Unique metering point identification
Metering point ID is not a cim term. It is entso-e, which we have agreed to use. GSRN is a danish implementation of a MP used for electricity, and is not suitable as a name for an integration event in GEH.

2021-07-06 12:51 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/Integration/IntegrationEvents/EnergySupplierChange/EnergySupplierChangedIntegrationEvent.proto
> +  string gsrn_number = 1; // Unique metering point identification
Also, may I suggest moving the currently unused contracts to a WIP folder, while removing the transaction id. As we are 100% know, and it is documented within the market, that a supplier change can be cancelled as well as initiated for a future date :)

2021-07-09 09:54 UTC, cmgrd approved these changes

2021-07-09 10:00 UTC, cmgrd approved these changes

2021-07-09 10:30 UTC, erduna approved these changes

2021-07-09 10:55 UTC, merged