add error conversion
Energinet-DataHub/geh-market-roles pull request #627
Opened 2021-07-06 13:13 UTC by cmgrd

Adds error conversion concept.
All error conversions are just TODO's for now - watch out for a later PR.

2021-07-07 06:56 UTC, kft submitted a review, later dismissed
LGTM

2021-07-07 08:58 UTC, erduna requested changes
I have added codes and descriptions where applicable

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/CannotBeInStateOfClosedDownRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("D16", $"The specified metering point has been closed down");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/ChangeOfSupplierRegisteredOnSameDateIsNotAllowedRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("D07", $"Effectuation date <1>(TODO: Insert effectuation date) incorrect: There is already another market transaction that takes precedence on date <2> (TODO: Insert effectuation date");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/CprNumberFormatRuleErrorConverter.cs
> +            return new("TODO", $"Description");
This one is interesting, as there can be several issues with a CPR that results in the same code but different descriptions.

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/CprNumberFormatRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("D17", $"Description");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/CvrNumberFormatRuleErrorConverter.cs
> +            return new("TODO", $"Description");
Same comment as for CPR converter

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/CvrNumberFormatRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("D17", $"Description");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/EffectuationDateCannotBeInThePastRuleErrorConverter.cs
> +    public class EffectuationDateCannotBeInThePastRuleErrorConverter : ErrorConverter<EffectuationDateCannotBeInThePastRuleError>
I believe the naming of this rule is wrong, and should more generally check for time parameters (including past and future). I know this is just a converter of the existing error and this comment is directed at the actual validation, but have to mention it anyways

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/EffectuationDateCannotBeInThePastRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("E17", $"Effectuation date (TODO: Insert date) incorrect: The information is not received within the correct time period (either too soon or too late)");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/EnergySupplierMustBeKnownRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("E16", $"Balance supplier (TODO: Insert GLN) for metering point (TODO: Insert GSRN) is not an authorized market party (organisation) on effectuation date (TODO: Insert effectuation date)");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/GlnNumberMustBeValidRuleErrorConverter.cs
> +            return new("TODO", $"Description");
This rule is kinda the same as the one above (EnergySupplierMustBeKnown). There is no specific code or error description provided focusing on a invalid GLN number besides the market party not being recognized.

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/GsrnNumberMustBeValidDomainErrorConverter.cs
> +            return new("E10", $"A metering point cannot be registered in GEH without a valid identification");
```suggestion
            return new("E10", $"GSRN (TODO: Insert GSRN) unknown: The specified metering point has not been registered in the system on effectuation date (TODO: Insert date)");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/GsrnNumberMustBeValidDomainErrorConverter.cs
> +            return new("E10", $"A metering point cannot be registered in GEH without a valid identification");
The code is the same, but in market roles we do not register any metering points, we just check for their existence, thus a different error text.

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/GsrnNumberMustBeValidRuleErrorConverter.cs
> +    public class GsrnNumberMustBeValidRuleErrorConverter : ErrorConverter<GsrnNumberMustBeValidRuleError>
What's the difference between the domain error above and this rule error? They check for the same thing?

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/GsrnNumberMustBeValidRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("E10", $"GSRN (TODO: Insert GSRN) unknown: The specified metering point has not been registered in the system on effectuation date (TODO: Insert date)");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/MeteringPointMustBeEnergySuppliableRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("E22", $"GLN code (TODO: insert GLN) not allowed: The specified production metering point (TODO: Insert GSRN) is blocked because it is subject to production obligation on the effectuation date (TODO: Insert date)");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/MeteringPointMustBeKnownRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("E10", $"GSRN (TODO: Insert GSRN) unknown: The specified metering point has not been registered in the system on effectuation date (TODO: Insert date)");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/MeteringPointMustBeKnownRuleErrorConverter.cs
> +            return new("TODO", $"Description");
This is again the same rule as 2 above rules. It seems this is the one we should keep, while removing the previous two.

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/MoveInRegisteredOnSameDateIsNotAllowedRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("D07", $"Effectuation date <1>(TODO: Insert effectuation date) incorrect: There is already another market transaction that takes precedence on date <2> (TODO: Insert effectuation date");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/MoveOutRegisteredOnSameDateIsNotAllowedRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("D07", $"Effectuation date <1>(TODO: Insert effectuation date) incorrect: There is already another market transaction that takes precedence on date <2> (TODO: Insert effectuation date");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/MoveOutRegisteredOnSameDateIsNotAllowedRuleErrorConverter.cs
> +            return new("TODO", $"Description");
We should consider giving a more telling error text now that we know what we are actually checking for. I am just inserting the actual error text given in the current system, where they generally check for interfering processes. Same goes for the few rules above that check for interference.

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/MustHaveEnergySupplierAssociatedRuleErrorConverter.cs
> +    public class MustHaveEnergySupplierAssociatedRuleErrorConverter : ErrorConverter<MustHaveEnergySupplierAssociatedRuleError>
Not sure what this rule checks, so can't look up code

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/ProductionMeteringPointMustBeObligatedRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("E22", $"GLN code (TODO: insert GLN) not allowed: The specified production metering point (TODO: Insert GSRN) is blocked because it is subject to production obligation on the effectuation date (TODO: Insert date)");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/SocialSecurityNumberMustBeValidRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("D17", $"Description");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/SocialSecurityNumberMustBeValidRuleErrorConverter.cs
> +            return new("TODO", $"Description");
Description can be several things depending on which SSN check it fails

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/StartOfSupplyMustBeValidRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("E17", $"Effectuation date (TODO: Insert date) incorrect: The information is not received within the correct time period (either too soon or too late)");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/StartOfSupplyMustBeValidRuleErrorConverter.cs
> +            return new("TODO", $"Description");
This should also be covered by a more general rule examining if date falls within specified parameters

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/TransactionMustBeValidRuleErrorConverter.cs
> +    public class TransactionMustBeValidRuleErrorConverter : ErrorConverter<TransactionMustBeValidRuleError>
Not sure what this checks?

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/VATNumberMustBeValidRuleErrorConverter.cs
> +            return new("TODO", $"Description");
```suggestion
            return new("D17", $"Description");
```

2021-07-07 08:58 UTC, erduna commented on source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure/EDI/Errors/Converters/VATNumberMustBeValidRuleErrorConverter.cs
> +            return new("TODO", $"Description");
Description varies based on which check fails

2021-07-07 09:44 UTC, erduna submitted a review, later dismissed

2021-07-08 07:08 UTC, kft approved these changes

2021-07-08 07:13 UTC, erduna approved these changes

2021-07-08 07:15 UTC, merged