Update ReceiveProtobuf to use simpleInjector
Energinet-DataHub/geh-market-roles pull request #657
Opened 2021-07-13 12:20 UTC by Korgath

## Description

Update ReceiveProtobuf to use simpleInjector

## References

* #0000

2021-07-13 12:30 UTC, cmgrd requested changes

2021-07-13 12:30 UTC, cmgrd commented on source/Energinet.DataHub.MarketRoles.Infrastructure/Transport/Protobuf/Integration/OneOfConfiguration.cs
> +        public OneOfConfiguration() { }
Why the change to public?

2021-07-13 12:30 UTC, cmgrd commented on source/Energinet.DataHub.MarketRoles.Infrastructure/Transport/Protobuf/Integration/OneOfConfiguration.cs
> +        public ProtobufParser GetParser()
Why the change to public?

2021-07-13 12:30 UTC, cmgrd commented on source/Energinet.DataHub.MarketRoles.IntegrationTests/Transport/TransportTests.cs
> +            var messageExtractor = container.GetInstance<MessageExtractor>();
This was previously organized in a sending part and a receiving part, now it's mixed. I think it was easier to follow before.

2021-07-13 18:58 UTC, Korgath commented
@cmgrd I would approve your changes, but can't since I'm the Author.. LGTM

2021-07-14 08:42 UTC, erduna submitted a review, later dismissed

2021-07-14 09:29 UTC, MrDach submitted a review, later dismissed

2021-07-14 11:01 UTC, MrDach submitted a review, later dismissed

2021-07-14 11:17 UTC, erduna approved these changes

2021-07-14 11:32 UTC, MrDach approved these changes

2021-07-14 11:33 UTC, cmgrd approved these changes

2021-07-14 11:33 UTC, merged