Implement transaction repository
Energinet-DataHub/geh-market-roles pull request #872
Opened 2022-03-29 10:36 UTC by Korgath

## Description

- Implement transaction repository
- Removed Transaction_is_Registered test

## References

* #0000

2022-03-29 10:45 UTC, kft commented on source/B2B.Transactions.Tests/TransactionHandlingTests.cs
> -
Why is this test removed ?

2022-03-29 10:47 UTC, Korgath commented on source/B2B.Transactions.Tests/TransactionHandlingTests.cs
> -
All it does is test DB implementation?

2022-03-29 10:47 UTC, kft commented on source/B2B.Transactions/DataAccess/MarketRolesContext.cs
> +    {
How about another name than MarketRoles ? B2BContext or something like that

2022-03-29 10:49 UTC, kft requested changes
I do not see a new test replacing the removed one. Why is this test not valid anymore ?

2022-03-29 10:51 UTC, Korgath commented on source/B2B.Transactions/DataAccess/MarketRolesContext.cs
> +    {
Aah yes ofc

2022-03-29 11:32 UTC, Korgath commented
As discussed with @kft - database implementation for testing will be implemented

2022-03-30 08:26 UTC, kft commented on source/B2B.Transactions.Tests/TransactionHandlingTests.cs
> +            await DisposeDatabaseAsync().ConfigureAwait(false);
Can we handle this in Dispose instead ? Does not seem relevant for the tests

2022-03-30 09:09 UTC, kft approved these changes

2022-03-30 09:19 UTC, merged