messagestore implementation
Energinet-DataHub/geh-market-roles pull request #911
Opened 2022-04-08 22:46 UTC by Mathiesen

## Description

Implement MessageStore 

## References

* #0000

2022-04-09 09:33 UTC, kft requested changes

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.CimMessageAdapter/Errors/DuplicateMessageIdDetected.cs
>              : base($"Message id '{messageId}' is not unique", "B2B-003")
Message id can never be null. Why this change ?

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.CimMessageAdapter/Errors/DuplicateTransactionIdDetected.cs
>              : base($"Transaction id '{transactionId}' is not unique and will not be processed.", "B2B-005")
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.CimMessageAdapter/Errors/UnknownReceiver.cs
>              : base($"Receiver id {receiverId} is not known receiver", "B2B-008")
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.CimMessageAdapter/Messages/IMessageIds.cs
>      }
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.CimMessageAdapter/Messages/ITransactionIds.cs
> +        Task<bool> TryStoreAsync(string? transactionId);
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.Infrastructure/DataAccess/Transaction/TransactionRepository.cs
>          {
Transaction id can never be null here.

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.Infrastructure/Messages/MessageIdRegistry.cs
>          {
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.Infrastructure/Messages/TransactionIdRegistry.cs
>          {
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.Infrastructure/OutgoingMessageStore.cs
> +                : new ReadOnlyCollection<OutgoingMessage>(retVal);
Why are we starting a new task here ? Why not just query the DbSet directly ?

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.Infrastructure/OutgoingMessages/MessagePublisher.cs
>                  new MessageTypeDto(string.Empty),
Recipient id should never be null.

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.IntegrationTests/Infrastructure/OutgoingMessages/MessagePublisherTests.cs
>          private readonly MessagePublisher _messagePublisher;
Null here ?

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.IntegrationTests/OutgoingMessageStoreTests.cs
> +        {
This test class not be needed at all. Outgoing message store is an implemenation details, and is test indirectly in the MessagePublisherTests

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.IntegrationTests/TestHelper.cs
> +        public IOutgoingMessageStore MessageStore { get; }
There is already a TransactionBuilder in the test project. No need for a TestHelper

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions.IntegrationTests/Transactions/TransactionHandlingTests.cs
Nullable ?

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/OutgoingMessages/AcceptMessage.cs
MessagePayload should not be changed after creation.

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/OutgoingMessages/AcceptMessage.cs
>      }
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/OutgoingMessages/IDocument.cs
> +        string MessagePayload { get; set; }
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/OutgoingMessages/IDocument.cs
> +        string DocumentType { get; set; }
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/OutgoingMessages/OutgoingMessage.cs
>          {
None of these can be null.

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/OutgoingMessages/OutgoingMessage.cs
Can't be null

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/OutgoingMessages/OutgoingMessage.cs
> +        }
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/Transactions/AcceptedTransaction.cs
> +        public AcceptedTransaction(string? transactionId)
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/Transactions/AcceptedTransaction.cs
> +        public string? TransactionId { get; }
Same as above

2022-04-09 09:33 UTC, kft commented on source/B2B.Transactions/Transactions/ITransactionRepository.cs
> +        AcceptedTransaction? GetById(string? transactionId);
Same as above

2022-04-11 10:53 UTC, CBrohus commented on source/B2B.Transactions.CimMessageAdapter/Errors/DuplicateTransactionIdDetected.cs
>              : base($"Transaction id '{transactionId}' is not unique and will not be processed.", "B2B-005")
Changed to non-nullable

2022-04-11 10:53 UTC, CBrohus commented on source/B2B.Transactions.CimMessageAdapter/Errors/UnknownReceiver.cs
>              : base($"Receiver id {receiverId} is not known receiver", "B2B-008")
Changed to non-nullable

2022-04-11 10:53 UTC, CBrohus commented on source/B2B.Transactions.CimMessageAdapter/Messages/IMessageIds.cs
>      }
Changed to non-nullable

2022-04-11 10:54 UTC, CBrohus commented on source/B2B.Transactions.CimMessageAdapter/Messages/ITransactionIds.cs
> +        Task<bool> TryStoreAsync(string? transactionId);
Changed to non-nullable

2022-04-11 10:54 UTC, CBrohus commented on source/B2B.Transactions.Infrastructure/Messages/MessageIdRegistry.cs
>          {
Changed to non-nullable

2022-04-11 10:54 UTC, CBrohus commented on source/B2B.Transactions.Infrastructure/Messages/TransactionIdRegistry.cs
>          {
Changed to non-nullable

2022-04-11 10:55 UTC, CBrohus commented on source/B2B.Transactions.Infrastructure/OutgoingMessageStore.cs
> +                : new ReadOnlyCollection<OutgoingMessage>(retVal);
Changed to query DBSet directly. Superfluous Task removed

2022-04-11 10:55 UTC, CBrohus commented on source/B2B.Transactions.Infrastructure/OutgoingMessages/MessagePublisher.cs
>                  new MessageTypeDto(string.Empty),
Changed to non-nullable

2022-04-11 10:55 UTC, CBrohus commented on source/B2B.Transactions.IntegrationTests/Infrastructure/OutgoingMessages/MessagePublisherTests.cs
>          private readonly MessagePublisher _messagePublisher;
Changed to non-nullable

2022-04-11 10:55 UTC, CBrohus commented on source/B2B.Transactions.IntegrationTests/Transactions/TransactionHandlingTests.cs
Changed to non-nullable

2022-04-11 10:56 UTC, CBrohus commented on source/B2B.Transactions/OutgoingMessages/AcceptMessage.cs
Changed to "init" to ensure MessagePayload can only be set once

2022-04-11 10:56 UTC, CBrohus commented on source/B2B.Transactions/OutgoingMessages/AcceptMessage.cs
>      }
Changed to "init" to ensure DocumentType can only be set once

2022-04-11 10:56 UTC, CBrohus commented on source/B2B.Transactions/OutgoingMessages/IDocument.cs
> +        string MessagePayload { get; set; }
Changed to "init" to ensure MessagePayload can only be set once

2022-04-11 10:57 UTC, CBrohus commented on source/B2B.Transactions/OutgoingMessages/IDocument.cs
> +        string DocumentType { get; set; }
Changed to "init" to ensure DocumentType can only be set once

2022-04-11 10:57 UTC, CBrohus commented on source/B2B.Transactions/OutgoingMessages/OutgoingMessage.cs
>          {
Changed to non-nullable

2022-04-11 10:57 UTC, CBrohus commented on source/B2B.Transactions/OutgoingMessages/OutgoingMessage.cs
Changed to non-nullable

2022-04-11 10:57 UTC, CBrohus commented on source/B2B.Transactions/OutgoingMessages/OutgoingMessage.cs
> +        }
Changed to non-nullable

2022-04-11 10:57 UTC, CBrohus commented on source/B2B.Transactions/Transactions/AcceptedTransaction.cs
> +        public AcceptedTransaction(string? transactionId)
Changed to non-nullable

2022-04-11 10:58 UTC, CBrohus commented on source/B2B.Transactions/Transactions/AcceptedTransaction.cs
> +        public string? TransactionId { get; }
Changed to non-nullable

2022-04-11 10:58 UTC, CBrohus commented on source/B2B.Transactions/Transactions/ITransactionRepository.cs
> +        AcceptedTransaction? GetById(string? transactionId);
Changed to non-nullable

2022-04-11 11:10 UTC, CBrohus commented on source/B2B.Transactions.IntegrationTests/TestHelper.cs
> +        public IOutgoingMessageStore MessageStore { get; }
Moved necessary code into TransactionBuilder and removed TestHelper.cs

2022-04-11 11:11 UTC, CBrohus commented on source/B2B.Transactions.IntegrationTests/OutgoingMessageStoreTests.cs
> +        {
Correct. The included test is already in MessagePublisherTests.

Deleted OutgoingMessageStoreTests.cs.

2022-04-11 12:21 UTC, merged