Ensure correlation id is sent to SB
Energinet-DataHub/geh-market-roles pull request #912
Opened 2022-04-11 12:11 UTC by Korgath

## Description

## References

* #0000

2022-04-19 14:45 UTC, kft commented on source/B2B.Transactions.Infrastructure/Configuration/ServiceBus/ServiceBusMessageMetadata.cs
> +    }
Can it really be null ?

2022-04-21 12:50 UTC, kft requested changes
We need to move middleware to host-layer

2022-04-27 06:48 UTC, MrDach approved these changes

2022-04-27 06:52 UTC, Mathiesen approved these changes

2022-04-27 06:52 UTC, Mathiesen commented on source/B2B.Transactions.Infrastructure/Transactions/TransactionQueueDispatcher.cs
> +        private const string CorrelationId = "Correlation-ID";
This will always be "Correlation-ID"???

2022-04-27 06:52 UTC, Mathiesen commented on source/B2B.Transactions.Infrastructure/Transactions/TransactionQueueDispatcher.cs
> +        private const string CorrelationId = "Correlation-ID";
nvm

2022-04-27 06:54 UTC, merged